
// Style
import 'bootstrap/dist/css/bootstrap.min.css';
import '@/styles/style.css'
import '@/styles/globals.css'

// Icon
import '../../public/icons/flaticon_mycollection.css';
import Head from 'next/head';
import Layout from '@/Components/Layout/Layout';

import { useRouter } from 'next/router';


export default function App({ Component, pageProps }) {

  const router = useRouter();

  if (router.pathname === '/login') {
    return (

      <>

        <Head>
          <title>Super Admin</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/images/favicon.png" />
        </Head>

        <Component {...pageProps} />

      </>

    )
  }

  return (

    <>

      <Head>
        <title>Super Admin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/favicon.png" />
      </Head>

      <Layout>
        <Component {...pageProps} />
      </Layout>


    </>

  )
}
